# Generated by Django 3.2.12 on 2024-02-22 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiry',
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_year',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
