# Generated by Django 3.2.12 on 2024-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20240222_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardholder_name',
            field=models.CharField(default='Error', max_length=255),
        ),
    ]
