# Generated by Django 3.2.12 on 2024-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_order_cardholder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small - €8.99'), ('Medium', 'Medium - €10.99'), ('Large', 'Large - €12.99'), ('Extra Large', 'Extra Large - €14.99'), ('Party Size', 'Party Size - €19.99')], max_length=20),
        ),
    ]
