# Generated by Django 3.2.12 on 2024-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_createpizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
