# Generated by Django 4.2.11 on 2025-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkingviolation_parkingspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actualEndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
