# Generated by Django 4.2.11 on 2025-02-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_actualendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
